local a=game:GetService("StarterGui")
local b=game:GetService("HttpService")
local d=loadstring(game:HttpGet("https://sirius.menu/rayfield"))()
repeat task.wait()until game:IsLoaded()
local e=d:CreateWindow({Name="ObservationHub | by R.K",LoadingTitle="ObservationHub",LoadingSubtitle="by R.K",ConfigurationSaving={Enabled=false},KeySystem=false})
local f=e:CreateTab("Main",4483362458)
f:CreateInput({Name="Enter Your Key",PlaceholderText="Paste your key here...",RemoveTextAfterFocusLost=false,Callback=function(g)if not g or g==""then d:Notify({Title="Error",Content="Please enter a valid key",Duration=5})return end
if g==c then d:Notify({Title="Success",Content="Click F to Enable and Disable your observation",Duration=5})
pcall(function()loadstring(game:HttpGet("https://raw.githubusercontent.com/legend09271/0bs3rvasy0n/refs/heads/main/ESP_Remote.lua"))()end)
task.delay(5,function()pcall(function()d:Destroy()end)end)else d:Notify({Title="Invalid Key",Content="Key not found or expired.",Duration=6})end end})
f:CreateButton({Name="Get Key",Callback=function()setclipboard("https://loot-link.com/s?BVGhj37v")
d:Notify({Title="Copied!",Content="Ad link copied to clipboard.",Duration=4})end})
d:Notify({Title="Get a Key",Content="Click OK to visit our ad link to generate a key.",Duration=6.5,Actions={Ignore={Name="OK",Callback=function()setclipboard("https://loot-link.com/s?BVGhj37v")
d:Notify({Title="Copied!",Content="Ad link copied to clipboard.",Duration=4})end}}})
